embedding_size: 64
n_layers: 2
reg_weight: [0.01]
learning_rate: [0.0001]
align_weight: [1.0]

epsilons: [0.025,0.05,0.075]
adv_weight: [8]
adv_align_weight: [8]
hyper_parameters: ["reg_weight", "learning_rate","align_weight","epsilons","adv_weight","adv_align_weight"]

# Parameters:['seed', 'reg_weight', 'learning_rate', 'align_weight']=(999, 0.01, 0.0001, 1.0),